// Generated by CoffeeScript 1.6.3
(function() {
  var bouncy, configs, http, net, req, socket, socketBounce, startProxy;

  configs = require('./configs');

  bouncy = require('bouncy');

  net = require('net');

  http = require('http');

  socket = configs.socket;

  startProxy = function() {
    var server;
    server = bouncy(socketBounce);
    server.listen(4243);
    return setTimeout(function() {
      server.close();
      return setTimeout(function() {
        return process.exit();
      }, 1000 * 60);
    }, configs.bounceWorkerLifeSpan + configs.bounceWorkerLifeSpan * Math.random());
  };

  req = http.request({
    socketPath: socket,
    path: '/version',
    method: 'GET'
  }, startProxy);

  req.on('error', function(err) {
    console.error('failed to connect', err);
    return (require('./register')).deregister();
  });

  req.end();

  socketBounce = function(req, res, bounce) {
    return bounce(net.connect(socket));
  };

}).call(this);

/*
//@ sourceMappingURL=bouncer.map
*/
