// Generated by CoffeeScript 1.6.3
(function() {
  var configs;

  configs = require('./configs');

  module.exports = require('redis').createClient(configs.redisPort, configs.redisHost);

}).call(this);

/*
//@ sourceMappingURL=client.map
*/
