// Generated by CoffeeScript 1.6.3
(function() {
  var configs, env, eson, os, path, readConfigs, uuid;

  eson = require('eson');

  os = require('os');

  path = require('path');

  uuid = require('node-uuid');

  env = process.env.NODE_ENV || 'development';

  readConfigs = function(filename) {
    return eson().read(__dirname + '/../configs/' + filename + '.json');
  };

  configs = module.exports = readConfigs(env);

  module.exports.readConfigs = readConfigs;

}).call(this);

/*
//@ sourceMappingURL=configs.map
*/
