// Generated by CoffeeScript 1.6.3
(function() {
  var Docker, bouncerPort, configs, dockerHost;

  configs = require('./configs');

  dockerHost = configs.docker_host;

  bouncerPort = configs.bouncer_port;

  Docker = require('dockerode');
  console.log("init dockerProxy");

  module.exports = function() {
    return new Docker({
      host: dockerHost,
      port: bouncerPort
    });
  };

}).call(this);

/*
//@ sourceMappingURL=dockerProxy.map
*/
