// Generated by CoffeeScript 1.6.3
(function() {
  var Docker, bouncerPort, configs, dockerHost;

  configs = require('./configs');

  dockerHost = configs.docker_host;

  bouncerPort = configs.bouncer_port;

  Docker = require('dockerode');
  var docker = new Docker({
      host: "http://localhost",
      port: bouncerPort
    });

docker.version(function(err, versionInfo) {
      if (err) {
        console.log("dockerVersion err: ", err);
      }
      console.log("dockerVersion versionInfo: ", versionInfo);
    });

  console.log("init dockerProxy");

  module.exports = function() {
    return docker;
  };

}).call(this);

/*
//@ sourceMappingURL=dockerProxy.map
*/
