// Generated by CoffeeScript 1.6.3
(function() {
  var docker;

  docker = require('./docker');

  module.exports = function(req, res, next) {
    req.body.job = true;
    return docker.findImage(req.body, function(err, ip) {
      if (err) {
        return res.send(err.code || 500, err.message);
      } else {
        return res.json(ip);
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=find.map
*/
