// Generated by CoffeeScript 1.6.3
(function() {
  var flatten, flattenImage, rollbar, uuid;

  uuid = require('node-uuid');

  flattenImage = global.test ? require('../test/fixtures/flattenDockerImages') : require('flattenDockerImages');

  rollbar = require('rollbar');

  flatten = module.exports = function(req, res, next) {
    var layerCount, newRepo, oldRepo;
    oldRepo = req.query.oldRepo;
    newRepo = req.query.newRepo || ('registry.runnable.com/runnable/' + uuid());
    layerCount = req.query.layerCount;
    return flattenImage(oldRepo, newRepo, layerCount, rollbar, function(err) {
      if (err) {
        console.error(err);
        return res.send(500, err.message);
      } else {
        return res.send(201);
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=flatten.map
*/
