// Generated by CoffeeScript 1.6.3
(function() {
  var app, configs, docker, env, nodetime, path, rollbar;

  path = require('path');

  env = require('./env');

  configs = require('./configs');

  rollbar = require('rollbar');

  path = require('path');

  if (configs.newRelicEnabled) {
    require('newrelic');
  }

  if (configs.rollbar) {
    rollbar.init(configs.rollbar, {
      environment: process.env.NODE_ENV || "development",
      branch: "master",
      root: path.resolve(__dirname, '..')
    });
  }

  if (configs.nodetime) {
    nodetime = require('nodetime');
    nodetime.profile(configs.nodetime);
  }

  docker = require('./docker');

  app = require('./app');

  app.use(rollbar.errorHandler());

  docker.cacheImages(function(err) {
    if (err) {
      console.error('failed to cache', err);
      return process.exit(1);
    } else {
      console.log('cached');
      require('./pubsub');
      (require('./register')).register();
      return app.listen(4244);
    }
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
