// Generated by CoffeeScript 1.6.3
(function() {
  var configs, ip;

  configs = require('./configs');

  ip = module.exports = configs.networkInterface === 'lo0' ? 'localhost' : require("os").networkInterfaces()[configs.networkInterface].filter(function(iface) {
    return iface.family === "IPv4";
  })[0].address;

}).call(this);

/*
//@ sourceMappingURL=ip.map
*/
