
# TODO: IMPLEMENT THIS WHOLE THING
# 1. WATCH SERVICE TABLE FOR ROW ADDITIONS
# 2. WHEN ROW IS ADDED, CHECK LOCAL DOCKER IMAGE CACHE IF AVAILABLE (PERIODICALLY UPDATE IN MEMORY LIST)
# 3. IF IMAGE IS NOT CACHED, ATTEMPT TO PULL DOWN IMAGE FROM DOCKER REGISTRY
# 4. ATTEMPT TO AQUIRE THE LOCK TO START RUNNING THE CONTAINER 
# 5. IF LOCK FAILS, THEN DONE
# 6. START A CONTAINER AND UPDATE TABLE ROW WITH TTL
# 7. WHEN THE CONTAINER IS RUNNING THEN UPDATE STATE TO "RUNNING" WITH DOCKER INDEX 
# 8. WRITE "ACTIVE" STATE WITH TTL VIA DOCKWORKER (OR FROM DOCKLET DIRECTLY)
# 9. STATE TRANSITIONS TO INACTIVE IF DOCKWORKER/MACHINE DIES

# TODO: IMPLEMENT THE BOOT SEQUENCE 
# 1. WALK THROUGH THE EXISTING SERVICE TABLE AND LOOK FOR ROWS IN RUNNING STATE OWNED BY US
# 2. FOR CONTAINERS OWNED BY US, START THEM BACK UP AGAIN (STATE SHOULD HAVE FLIPPED TO INACTIVE)
