

# TODO: IMPLEMENT THIS WHOLE THING
# 1. WATCH SERVICE TABLE FOR ROW ADDITIONS
# 2. WHEN ROW IS ADDED, CHECK LOCAL DOCKER IMAGE CACHE IF AVAILABLE (PERIODICALLY UPDATE IN MEMORY LIST)
# 3. IF IMAGE IS NOT CACHED, ATTEMPT TO PULL DOWN IMAGE FROM DOCKER REGISTRY
# 4. ATTEMPT TO AQUIRE THE LOCK TO START RUNNING THE CONTAINER 
# 5. IF LOCK FAILS, THEN DONE
# 6. START A CONTAINER AND UPDATE TABLE ROW WITH TTL
# 7. WHEN THE CONTAINER IS RUNNING THEN UPDATE STATE TO "RUNNING" WITH DOCKER INDEX 
